# Generated by Django 6.0.2 on 2026-02-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='content',
            field=models.CharField(max_length=11),
        ),
    ]
