# Generated by Django 6.0.2 on 2026-02-27 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_auth', '0002_alter_patients_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
