# Generated by Django 6.0.2 on 2026-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_auth', '0003_patients_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
