# Generated by Django 6.0.3 on 2026-05-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_auth', '0004_alter_patients_address_alter_patients_patient_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('temperature', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='content',
            new_name='contect',
        ),
        migrations.AlterField(
            model_name='patients',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
