# Generated by Django 6.0.3 on 2026-05-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b_auth', '0005_checkup_history_rename_content_patients_contect_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='contect',
            new_name='contact',
        ),
    ]
